import { Injectable } from '@angular/core';
import { Amigo } from '../models/amigos';

const AMIGOS: Amigo[] = [
  {
    id: 'dado',
    name: 'Diego',
    middle_name: 'Enrique',
    last_name: 'Cáceres',
    nick_name: 'Dado',
    dob: '12/27/1990',
    has_tattoo_of_house: true,
    hobbies: ['Batería', 'Surf', 'Juegos de Caja'],
    thumbnail: '/dado-thumbnail.png',
    photos: { dir: '/dado', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'gero',
    name: 'Gerónimo',
    middle_name: null,
    last_name: 'García',
    nick_name: 'Gero',
    dob: '07/27/1994',
    has_tattoo_of_house: false,
    hobbies: ['Gaming', 'Bicicleta', 'Anime', 'Juegos de Caja'],
    thumbnail: '/gero-thumbnail.png',
    photos: { dir: '/gero', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'leo',
    name: 'Leonardo',
    middle_name: 'Germán',
    last_name: 'Paller',
    nick_name: 'Leo',
    dob: '03/01/1990',
    has_tattoo_of_house: false,
    hobbies: [
      'Reading',
      'Drinking',
      'PCGaming',
      'Travelling',
      'Watching series',
    ],
    thumbnail: '/leo-thumbnail.png',
    photos: { dir: '/leo', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'santi',
    name: 'Santiago',
    middle_name: null,
    last_name: 'Rivero',
    nick_name: 'Santi',
    dob: '11/07/1992',
    has_tattoo_of_house: false,
    hobbies: ['Música', 'Bailar'],
    thumbnail: '/santi-thumbnail.png',
    photos: { dir: '/santi', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'moui',
    name: 'Mauricio',
    middle_name: 'Daniel',
    last_name: 'Barrera',
    nick_name: 'Moui',
    dob: '08/12/1994',
    has_tattoo_of_house: false,
    hobbies:  ['Fumar porro', 'Comer', 'Plantar porro', 'Tomar cerveza', 'Dormir'],
    thumbnail: '/moui-thumbnail.png',
    photos: { dir: '/moui', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'gambo',
    name: 'Gabriel',
    middle_name: 'Alejandro',
    last_name: 'Martínez',
    nick_name: 'Gambo',
    dob: '04/14/1995',
    has_tattoo_of_house: false,
    hobbies: ['Videojuegos', 'Juegos de caja', 'Anime', 'Cocinar', 'Platas'],
    thumbnail: '/gambo-thumbnail.png',
    photos: { dir: '/gambo', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'lucas',
    name: 'Lucas',
    middle_name: null,
    last_name: 'Ramírez',
    nick_name: null,
    dob: '01/01/1111',
    has_tattoo_of_house: false,
    hobbies: ['Rap', 'Porro', 'Deportes'],
    thumbnail: '/lucas-thumbnail.png',
    photos: { dir: '/lucas', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'bruno',
    name: 'Bruno',
    middle_name: null,
    last_name: 'Tortarolo',
    nick_name: null,
    dob: '12/10/1993',
    has_tattoo_of_house: true,
    hobbies: ['Anime', 'Música', 'Bicicleta'],
    thumbnail: '/bruno-thumbnail.png',
    photos: { dir: '/bruno', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'anita',
    name: 'Anaclara',
    middle_name: null,
    last_name: 'Couto',
    nick_name: 'Anita',
    dob: '10/31/1994',
    has_tattoo_of_house: false,
    hobbies: [
      'Competir con Gero',
      'Escuchar cumbia villera ',
      'Jugar al tetris',
      'Dormir la siesta',
      'Seguirle la vida a las mormonas',
    ],
    thumbnail: '/anita-thumbnail.png',
    photos: {
      dir: '/anita',
      images: ['1', '2', '3', '4', '5'],
    },
  },
  {
    id: 'pau',
    name: 'Paula',
    middle_name: null,
    last_name: 'Tortarolo',
    nick_name: 'Pau',
    dob: '09/01/1995',
    has_tattoo_of_house: false,
    hobbies: ['Rap', 'Porro', 'Dibujar'],
    thumbnail: '/pau-thumbnail.png',
    photos: { dir: '/pau', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'flor',
    name: 'Florencia',
    middle_name: 'María',
    last_name: 'Navarro',
    nick_name: 'Flor',
    dob: '01/01/1111',
    has_tattoo_of_house: false,
    hobbies: ['Jugar video juegos', 'Nadar', 'Viajar', 'Trekking', 'Bailar'],
    thumbnail: '/flor-thumbnail.png',
    photos: { dir: '/flor', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'muri',
    name: 'Muriel',
    middle_name: null,
    last_name: 'Dathaguy',
    nick_name: 'Muri',
    dob: '01/01/1111',
    has_tattoo_of_house: false,
    hobbies: ['Juegos de Caja', 'Series'],
    thumbnail: '/muri-thumbnail.png',
    photos: { dir: '/muri', images: ['1', '2', '3', '4', '5'] },
  },
  {
    id: 'belu',
    name: 'Belén',
    middle_name: 'María',
    last_name: 'Fernández',
    nick_name: 'Belu',
    dob: '01/02/1997',
    has_tattoo_of_house: false,
    hobbies: ['Guitarra', 'Cantar', 'Cocinar cosas dulces', 'Ser fan de BTS'],
    thumbnail: '/belu-thumbnail.png',
    photos: { dir: '/belu', images: ['1', '2', '3', '4', '5'] },
  },
];

@Injectable({
  providedIn: 'root',
})
export class AmiDataService {
  constructor() {}

  fetchAmiList(): Amigo[] {
    return AMIGOS;
  }

  fetchSingleAmi(id: string): Amigo {
    let amigo: Amigo = AMIGOS.filter((ami) => ami.id === id)[0];
    return amigo;
  }
}
